# Generated by Django 5.2 on 2025-05-02 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulationMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_days", models.PositiveIntegerField()),
                ("final_overall_cost", models.BigIntegerField()),
                ("simulation_start_time", models.DateTimeField(auto_now_add=True)),
                ("simulation_end_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WallProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_index",
                    models.PositiveIntegerField(
                        help_text="1-based index from the input file", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.PositiveIntegerField(db_index=True)),
                ("is_overall", models.BooleanField(db_index=True, default=False)),
                ("ice_yards_today", models.PositiveIntegerField(default=0)),
                ("cost_today", models.BigIntegerField(default=0)),
                ("cumulative_cost", models.BigIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if this is an overall record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction_api.wallprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "is_overall", "profile__original_index"],
                "indexes": [
                    models.Index(
                        fields=["day", "is_overall"], name="constructio_day_605be8_idx"
                    )
                ],
                "unique_together": {("day", "profile", "is_overall")},
            },
        ),
        migrations.CreateModel(
            name="WallSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_index",
                    models.PositiveIntegerField(
                        help_text="0-based index within the profile"
                    ),
                ),
                ("initial_height", models.IntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="construction_api.wallprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["profile__original_index", "section_index"],
                "unique_together": {("profile", "section_index")},
            },
        ),
    ]
